
insert into public.technologies (name, slug, category, sort_order) values
 ('OpenAI','openai','AI',10),('Anthropic Claude','anthropic','AI',20),('LangChain','langchain','AI',30),
 ('Vector databases','vector-db','Data',40),('n8n','n8n','Automation',50),('Make','make','Automation',60),
 ('REST & GraphQL APIs','apis','Integration',70),('PostgreSQL','postgresql','Data',80),
 ('Supabase','supabase','Data',90),('TypeScript','typescript','Engineering',100),
 ('React','react','Engineering',110),('Node.js','nodejs','Engineering',120),
 ('Python','python','Engineering',130),('Docker','docker','Infrastructure',140),
 ('OWASP','owasp','Security',150),('Zero Trust','zero-trust','Security',160)
on conflict (slug) do nothing;

insert into public.services (slug, title, summary, icon, status, published_at, is_featured, sort_order, seo_title, seo_description, content) values
('ai-agents','AI Agents','Des agents intelligents qui exécutent réellement des tâches dans vos systèmes, avec un périmètre et des garde-fous définis.','bot','published', now(), true, 10,
 'AI Agents pour entreprises — Zawena','Zawena conçoit des agents IA connectés à vos outils métier : périmètre défini, garde-fous, supervision humaine.',
 '{"eyebrow":"AI Agents","benefit":"Déléguer les tâches répétitives à des agents supervisés, sans perte de contrôle.","problem":["Les équipes passent des heures sur des tâches répétitives à faible valeur.","Les informations utiles sont dispersées entre plusieurs outils.","Les assistants génériques ne savent pas agir dans vos systèmes."],"solution":"Nous concevons des agents spécialisés, connectés à vos outils, avec un périmètre d''action explicite, une traçabilité complète et une validation humaine sur les actions sensibles.","capabilities":[{"title":"Agents commerciaux","description":"Qualification des demandes entrantes, enrichissement CRM, préparation de relances."},{"title":"Agents support client","description":"Réponses assistées sur votre base de connaissances, tri et routage des tickets."},{"title":"Agents RH","description":"Pré-analyse de candidatures, réponses aux questions internes, préparation d''onboarding."},{"title":"Agents finance","description":"Rapprochements, extraction de documents, contrôles de cohérence."},{"title":"Agents opérations","description":"Suivi des flux, alertes, comptes rendus automatiques."},{"title":"Agents cybersécurité","description":"Synthèse d''alertes, priorisation, aide à l''investigation."}],"useCases":["Un agent qui qualifie chaque demande entrante et crée le prospect dans le CRM.","Un agent qui prépare une réponse support en citant ses sources internes.","Un agent qui produit chaque matin un rapport d''activité consolidé."],"technologies":["OpenAI","Anthropic Claude","LangChain","Vector databases","PostgreSQL","TypeScript"],"faq":[{"question":"Les agents agissent-ils sans supervision ?","answer":"Non. Chaque action sensible passe par une validation humaine, sauf décision explicite de votre part sur un périmètre restreint."},{"question":"Peut-on connecter un agent à nos outils actuels ?","answer":"Oui, dès qu''une API ou une base de données est accessible. Nous cadrons les accès au strict nécessaire."}]}'::jsonb),

('ai-automation','AI Automation','Automatisation de workflows métier de bout en bout, avec de l''IA là où elle apporte une valeur mesurable.','workflow','published', now(), true, 20,
 'Automatisation de processus métier — Zawena','Workflows automatisés (n8n, Make, APIs) reliant CRM, ERP et outils internes, renforcés par l''IA quand c''est utile.',
 '{"eyebrow":"AI Automation","benefit":"Supprimer les tâches manuelles entre vos outils et réduire les délais de traitement.","problem":["Les données sont recopiées manuellement d''un outil à l''autre.","Les processus dépendent de rappels humains et de fichiers partagés.","Personne ne sait précisément où un dossier est bloqué."],"solution":"Nous cartographions le processus, automatisons les étapes déterministes, ajoutons de l''IA sur les étapes qui demandent de l''interprétation, et rendons chaque exécution observable.","capabilities":[{"title":"Cartographie des processus","description":"Analyse des étapes, des acteurs et des points de blocage réels."},{"title":"Workflows n8n / Make","description":"Orchestration fiable, gestion des erreurs et des reprises."},{"title":"Automatisations sur mesure","description":"Quand l''outil no-code ne suffit plus, nous développons le service dédié."},{"title":"Connexion CRM & ERP","description":"Synchronisation des données de référence sans doublons."},{"title":"Documents intelligents","description":"Extraction et structuration d''informations depuis PDF, emails, formulaires."},{"title":"Observabilité","description":"Journalisation, alertes et tableaux de suivi des exécutions."}],"useCases":["Demande entrante → qualification → création CRM → notification → devis préparé.","Facture reçue → extraction → contrôle → mise en attente de validation.","Rapport hebdomadaire consolidé et diffusé automatiquement."],"technologies":["n8n","Make","REST & GraphQL APIs","PostgreSQL","Node.js","Python"],"faq":[{"question":"Faut-il remplacer nos outils actuels ?","answer":"Rarement. Nous automatisons d''abord autour de l''existant et ne recommandons un remplacement que s''il est justifié."},{"question":"Comment mesurez-vous le gain ?","answer":"Nous définissons avant le projet les indicateurs suivis : temps de traitement, volume traité, taux d''erreur."}]}'::jsonb),

('ai-integration','AI Integration','Intégration de l''IA dans vos systèmes existants : applications, CRM, ERP, bases de données.','plug','published', now(), true, 30,
 'Intégration de l''IA aux systèmes existants — Zawena','Zawena intègre LLM et services IA à vos applications, CRM, ERP et bases de données, avec sécurité et coûts maîtrisés.',
 '{"eyebrow":"AI Integration","benefit":"Ajouter des capacités IA à vos systèmes sans les reconstruire.","problem":["Les démonstrations IA ne survivent pas au passage en production.","Les données nécessaires sont enfermées dans des systèmes hétérogènes.","Les coûts et la confidentialité ne sont pas maîtrisés."],"solution":"Nous traitons l''IA comme un composant d''architecture : contrats d''interface clairs, accès aux données contrôlés, mise en cache, suivi des coûts et évaluation de la qualité des réponses.","capabilities":[{"title":"Couche d''intégration LLM","description":"Abstraction des fournisseurs, gestion des quotas et des reprises."},{"title":"Recherche sur vos données","description":"Indexation et récupération contextuelle sur vos contenus internes."},{"title":"APIs & webhooks","description":"Exposition propre des capacités IA à vos applications."},{"title":"CRM & ERP","description":"Enrichissement et automatisation au sein des outils déjà utilisés."},{"title":"Bases de données","description":"Accès contrôlé, projections explicites, aucune donnée superflue exposée."},{"title":"Évaluation & garde-fous","description":"Jeux de tests, seuils de confiance, journalisation des réponses."}],"useCases":["Recherche interne en langage naturel sur la documentation d''entreprise.","Résumé automatique des échanges clients directement dans le CRM.","Classification et routage des emails entrants."],"technologies":["OpenAI","Anthropic Claude","Vector databases","REST & GraphQL APIs","Supabase","PostgreSQL"],"faq":[{"question":"Nos données servent-elles à entraîner des modèles ?","answer":"Non. Nous privilégions des configurations qui excluent l''entraînement sur vos données et limitons les informations transmises."},{"question":"Peut-on changer de modèle plus tard ?","answer":"Oui, c''est précisément le rôle de la couche d''intégration que nous mettons en place."}]}'::jsonb),

('ai-applications','AI Applications','Applications et plateformes web intelligentes : SaaS, portails métier, dashboards décisionnels.','layout-dashboard','published', now(), true, 40,
 'Applications et plateformes IA sur mesure — Zawena','Zawena conçoit des applications web intelligentes : SaaS, portails métier et dashboards, pensés pour l''usage réel.',
 '{"eyebrow":"AI Applications","benefit":"Un produit utilisable au quotidien, pas une démonstration.","problem":["Les tableurs deviennent le système d''information de fait.","Les outils internes existants sont lents et peu utilisés.","Les données existent mais ne sont pas exploitables pour décider."],"solution":"Nous concevons produit, interface et architecture ensemble : parcours clairs, états de chargement et d''erreur traités, données fiables, IA intégrée là où elle fait gagner du temps.","capabilities":[{"title":"Plateformes SaaS","description":"Multi-utilisateurs, rôles, facturation et journalisation."},{"title":"Portails métier","description":"Outils internes qui remplacent réellement les tableurs."},{"title":"Dashboards","description":"Indicateurs lisibles, filtres, exports."},{"title":"Interfaces assistées","description":"Recherche, suggestions et rédaction assistée intégrées au parcours."},{"title":"Design system","description":"Composants cohérents, accessibles et réutilisables."},{"title":"Qualité produit","description":"Accessibilité, performance et responsive traités dès la conception."}],"useCases":["Un portail de gestion des demandes clients avec suivi de statut.","Un dashboard de pilotage commercial consolidé.","Une application interne de traitement documentaire assisté."],"technologies":["React","TypeScript","Supabase","PostgreSQL","Node.js"],"faq":[{"question":"Livrez-vous par étapes ?","answer":"Oui. Nous livrons un périmètre utilisable rapidement, puis nous étendons selon les usages constatés."},{"question":"Restons-nous propriétaires du code ?","answer":"Oui, le code et les données vous appartiennent."}]}'::jsonb),

('software-engineering','Software Engineering','Développement logiciel sur mesure : frontend, backend, APIs, architecture et bases de données.','code-2','published', now(), true, 50,
 'Développement logiciel sur mesure — Zawena','Ingénierie logicielle Zawena : architecture, APIs, backend, frontend et bases de données conçus pour durer.',
 '{"eyebrow":"Software Engineering","benefit":"Une base technique maintenable, qui ne devient pas une dette dans un an.","problem":["Les applications existantes sont difficiles à faire évoluer.","Les règles métier sont dispersées dans l''interface.","Les incidents sont découverts par les utilisateurs."],"solution":"Nous plaçons les règles métier côté serveur, définissons des contrats d''API explicites, modélisons les données avec rigueur et rendons le système observable.","capabilities":[{"title":"Architecture","description":"Découpage par domaine, frontières explicites, décisions documentées."},{"title":"Backend & APIs","description":"Validation systématique, autorisation serveur, idempotence."},{"title":"Frontend","description":"Interfaces typées, états asynchrones complets, accessibilité."},{"title":"Bases de données","description":"Modélisation, index, contraintes, migrations versionnées."},{"title":"Intégrations","description":"Connexion aux systèmes tiers avec gestion des pannes."},{"title":"Qualité","description":"Revue de code, journalisation, audit des actions sensibles."}],"useCases":["Reprise et assainissement d''une application existante.","Construction d''une API métier destinée à plusieurs clients internes.","Modernisation progressive d''un système vieillissant."],"technologies":["TypeScript","React","Node.js","Python","PostgreSQL","Docker"],"faq":[{"question":"Travaillez-vous sur du code existant ?","answer":"Oui. Nous commençons par un audit court avant toute intervention structurelle."},{"question":"Comment gérez-vous la reprise du projet en interne ?","answer":"Documentation, revue partagée et transfert de compétences font partie de la livraison."}]}'::jsonb),

('cybersecurity','Cybersecurity','Audit, analyse de vulnérabilités, tests d''intrusion et sécurisation applicative et infrastructure.','shield-check','published', now(), true, 60,
 'Audit et sécurité des systèmes — Zawena','Zawena évalue et renforce la sécurité de vos applications et infrastructures : audit, vulnérabilités, pentest, recommandations priorisées.',
 '{"eyebrow":"Cybersecurity","benefit":"Savoir précisément où vous êtes exposé, et dans quel ordre corriger.","problem":["Les droits d''accès s''accumulent sans revue.","Les dépendances ne sont pas suivies.","Les correctifs sont décidés sans priorisation claire."],"solution":"Nous évaluons votre exposition réelle, documentons les constats avec un niveau de gravité, et livrons un plan de correction priorisé et réaliste.","capabilities":[{"title":"Audit de sécurité","description":"Revue de l''architecture, des accès et des configurations."},{"title":"Analyse de vulnérabilités","description":"Dépendances, surfaces exposées, erreurs de configuration."},{"title":"Tests d''intrusion","description":"Scénarios d''attaque cadrés et autorisés."},{"title":"Sécurité applicative","description":"Authentification, autorisation, validation des entrées, journalisation."},{"title":"Sécurité infrastructure","description":"Cloisonnement réseau, secrets, sauvegardes, moindre privilège."},{"title":"Recommandations","description":"Plan d''action hiérarchisé, avec effort et impact estimés."}],"useCases":["Audit avant une mise en production sensible.","Revue des accès et des secrets après une phase de croissance rapide.","Renforcement d''une application exposée sur Internet."],"technologies":["OWASP","Zero Trust","Docker","PostgreSQL"],"faq":[{"question":"Un test d''intrusion peut-il perturber la production ?","answer":"Le périmètre, les horaires et les limites sont contractualisés avant tout test."},{"question":"Livrez-vous un rapport exploitable ?","answer":"Oui : constats, gravité, preuve, et correction recommandée pour chaque point."}]}'::jsonb),

('ai-consulting','AI Consulting','Stratégie, architecture et feuille de route : savoir où et comment l''IA crée de la valeur chez vous.','compass','published', now(), true, 70,
 'Conseil et stratégie IA — Zawena','Zawena aide les organisations à identifier les cas d''usage IA rentables et à construire une feuille de route réaliste.',
 '{"eyebrow":"AI Consulting","benefit":"Investir sur les cas d''usage qui ont un retour mesurable, et écarter les autres.","problem":["Beaucoup d''idées IA, peu de critères pour les prioriser.","Des expérimentations qui n''atteignent jamais la production.","Des équipes non préparées aux nouveaux outils."],"solution":"Nous partons de vos processus, identifions les cas d''usage à valeur mesurable, évaluons faisabilité et risques, puis construisons une feuille de route séquencée.","capabilities":[{"title":"Audit IA","description":"État des lieux des processus, données et outils."},{"title":"Priorisation","description":"Valeur, effort, risque et dépendances pour chaque cas d''usage."},{"title":"Architecture cible","description":"Choix techniques, intégrations et trajectoire de migration."},{"title":"Feuille de route","description":"Séquencement par jalons livrables."},{"title":"Gouvernance","description":"Confidentialité, traçabilité, contrôle humain."},{"title":"Formation","description":"Montée en compétence des équipes concernées."}],"useCases":["Cadrage d''un premier projet IA à périmètre maîtrisé.","Arbitrage entre plusieurs initiatives concurrentes.","Définition d''une politique interne d''usage de l''IA."],"technologies":["OpenAI","Anthropic Claude","PostgreSQL","REST & GraphQL APIs"],"faq":[{"question":"Le conseil peut-il rester indépendant de la réalisation ?","answer":"Oui. Le cadrage est un livrable autonome, exploitable par l''équipe de votre choix."},{"question":"Combien de temps dure un cadrage ?","answer":"Généralement de une à trois semaines selon le nombre de processus étudiés."}]}'::jsonb)
on conflict (slug) do nothing;

insert into public.projects (slug, title, summary, status, published_at, is_featured, sort_order, industry, client_name, seo_title, seo_description, content) values
('agent-support-concept','Agent de support connecté à une base de connaissances','Concept d''agent IA qui prépare des réponses support sourcées et route les demandes complexes vers un humain.','published', now(), true, 10, 'Support client', 'Concept',
 'Concept — Agent de support IA sourcé | Zawena','Concept Zawena : un agent de support qui cite ses sources internes et escalade les cas complexes.',
 '{"kind":"Concept","category":"AI","challenge":"Les équipes support répondent plusieurs fois par jour aux mêmes questions, tandis que la documentation interne reste sous-utilisée.","approach":["Indexation de la documentation interne avec récupération contextuelle.","Réponse proposée systématiquement accompagnée de ses sources.","Escalade automatique vers un agent humain sous un seuil de confiance."],"outcome":"Concept fonctionnel démontrant le parcours complet, sans mesure client publiée.","technologies":["OpenAI","Vector databases","PostgreSQL","React"]}'::jsonb),

('workflow-devis-interne','Chaîne devis automatisée de bout en bout','Projet interne : de la demande entrante au devis préparé, avec traçabilité et validation humaine.','published', now(), true, 20, 'Opérations', 'Projet interne',
 'Projet interne — Chaîne de devis automatisée | Zawena','Projet interne Zawena : automatisation de la chaîne demande → prospect → devis, avec audit complet.',
 '{"kind":"Internal Project","category":"Automation","challenge":"Traiter les demandes entrantes sans ressaisie manuelle et sans perdre la trace des décisions.","approach":["Formulaire validé côté serveur et protection anti-abus.","Création ou enrichissement automatique du prospect, sans fusion silencieuse.","Numérotation, versionnage et immuabilité des devis envoyés.","Journal d''audit sur chaque opération sensible."],"outcome":"Utilisé en interne par Zawena pour ses propres demandes entrantes.","technologies":["TypeScript","PostgreSQL","Supabase","n8n"]}'::jsonb),

('portail-operations-prototype','Portail de pilotage des opérations','Prototype de dashboard interne consolidant pipeline commercial, tickets et facturation.','published', now(), true, 30, 'SaaS interne', 'Prototype',
 'Prototype — Portail de pilotage des opérations | Zawena','Prototype Zawena de dashboard interne : pipeline, support et facturation dans une vue unique.',
 '{"kind":"Prototype","category":"Software","challenge":"Les indicateurs de pilotage étaient répartis entre plusieurs outils et fichiers.","approach":["Modèle de données unifié avec accès contrôlé par rôle.","Vues agrégées calculées en base plutôt que côté interface.","États de chargement, vides et d''erreur traités pour chaque bloc."],"outcome":"Prototype interne servant de socle au futur portail client.","technologies":["React","TypeScript","PostgreSQL","Supabase"]}'::jsonb),

('durcissement-securite-interne','Durcissement de la sécurité applicative','Projet interne : revue des accès, des politiques de données et des dépendances de notre propre plateforme.','published', now(), false, 40, 'Cybersécurité', 'Projet interne',
 'Projet interne — Durcissement de la sécurité applicative | Zawena','Projet interne Zawena : moindre privilège, politiques de données par rôle et suivi des dépendances.',
 '{"kind":"Internal Project","category":"Cybersecurity","challenge":"Garantir qu''aucune donnée privée ne soit accessible depuis une route publique.","approach":["Politiques d''accès par rôle appliquées directement en base.","Séparation stricte des lectures publiques et des lectures internes.","Autorisation vérifiée côté serveur sur chaque opération sensible.","Revue régulière des dépendances et des secrets."],"outcome":"Appliqué à la plateforme Zawena, revu en continu.","technologies":["OWASP","Zero Trust","PostgreSQL","Supabase"]}'::jsonb)
on conflict (slug) do nothing;

insert into public.projects (slug, title, summary, status, published_at, is_featured, sort_order, industry, client_name, content) values
('cadrage-ia-concept','Cadrage IA et feuille de route','Concept de méthode de cadrage : inventaire des processus, priorisation des cas d''usage et trajectoire.','published', now(), false, 50, 'Conseil', 'Concept',
 '{"kind":"Concept","category":"Consulting","challenge":"Choisir objectivement quel cas d''usage IA financer en premier.","approach":["Inventaire des processus et des données disponibles.","Notation valeur / effort / risque pour chaque cas d''usage.","Feuille de route séquencée par jalons livrables."],"outcome":"Méthode de cadrage utilisée par Zawena lors de ses missions de conseil.","technologies":["PostgreSQL","OpenAI"]}'::jsonb)
on conflict (slug) do nothing;

insert into public.projects (slug, title, summary, status, published_at, is_featured, sort_order, industry, client_name, content) values
('integration-crm-erp-concept','Passerelle d''intégration CRM ↔ ERP','Concept de passerelle de synchronisation bidirectionnelle avec résolution des conflits.','published', now(), false, 60, 'Intégration', 'Concept',
 '{"kind":"Concept","category":"AI","challenge":"Maintenir des données de référence cohérentes entre deux systèmes qui ne se connaissent pas.","approach":["Contrat de données explicite et projections limitées au nécessaire.","Idempotence sur chaque synchronisation.","Journal des conflits avec arbitrage humain."],"outcome":"Concept technique validé sur jeux de données de test.","technologies":["REST & GraphQL APIs","Node.js","PostgreSQL"]}'::jsonb)
on conflict (slug) do nothing;

insert into public.project_technologies (project_id, technology_id)
select p.id, t.id
from public.projects p
join lateral jsonb_array_elements_text(coalesce(p.content->'technologies','[]'::jsonb)) as tech(name) on true
join public.technologies t on t.name = tech.name
on conflict do nothing;

insert into public.service_technologies (service_id, technology_id)
select s.id, t.id
from public.services s
join lateral jsonb_array_elements_text(coalesce(s.content->'technologies','[]'::jsonb)) as tech(name) on true
join public.technologies t on t.name = tech.name
on conflict do nothing;

insert into public.faqs (question, answer, category, status, sort_order) values
('Que peut concrètement automatiser Zawena ?','Tout processus répétitif dont les étapes sont identifiables : traitement des demandes entrantes, synchronisation entre outils, extraction de documents, reporting, relances. Nous commençons toujours par cartographier le processus réel avant d''automatiser.','general','published',10),
('Combien coûte un agent IA ?','Le coût dépend du nombre de systèmes connectés, du niveau de contrôle exigé et du volume traité. Nous établissons un chiffrage après un cadrage court ; vous pouvez demander un devis pour obtenir une estimation adaptée à votre contexte.','pricing','published',20),
('Pouvez-vous intégrer l''IA à notre logiciel existant ?','Oui, dès qu''une API ou un accès base de données est disponible. Notre approche consiste à ajouter une couche d''intégration plutôt qu''à reconstruire votre système.','general','published',30),
('Travaillez-vous avec les PME ?','Oui. Nous cadrons le périmètre pour livrer un premier résultat utile rapidement, puis nous étendons selon les usages réellement constatés.','general','published',40),
('Quels systèmes pouvez-vous intégrer ?','CRM, ERP, outils de support, bases de données, services internes et APIs tierces. Nous vérifions la faisabilité pendant le cadrage, avant tout engagement.','general','published',50),
('Proposez-vous des audits de cybersécurité ?','Oui : audit d''architecture et d''accès, analyse de vulnérabilités et tests d''intrusion cadrés. Chaque constat est livré avec un niveau de gravité et une correction recommandée.','security','published',60),
('Comment démarre un projet ?','Par un échange de cadrage, suivi d''une proposition écrite décrivant périmètre, livrables, jalons et hypothèses. La réalisation ne commence qu''après validation.','process','published',70),
('Nos données sont-elles utilisées pour entraîner des modèles ?','Non. Nous privilégions des configurations excluant l''entraînement sur vos données et limitons strictement les informations transmises aux services externes.','security','published',80)
on conflict do nothing;
